### ISSUE TITLE
Additional non ASCII telegrams

### ISSUE THREAD

**Issue by Nothinel** [electronsandstuff/py-pfeiffer-vacuum-protocol#1]
Hi there,

thank you for the great work! 

In short: changing line 41 to 
``` Python
if not (c == b"\xff"): r += c.decode("ascii")
```
Will make this work for our set up, which is:
HiCube 80 Eco/MVP 015-2 (pump system from Pfeiffer)
MPT 200 AR, Digital Pirani
and for the serial communication:
Renkforce USB 1.1 Adapter (from RS485 to RS232 and from there to USB) 
At the beginning of the read_out, and only with this specific Adapter from RS232 to USB( we tested some others) we will always receive 40 times  b"\xff" before the actual message. b"\xff" cannot be decoded into ascii and hence the program crashes. This can be omitted with the above check for those characters at a marginal cost. If you have a more pythonic, more elegant or plain better solution, we are more than happy to learn. Otherwise this small change would make this great module usable for another set of hardware.
If you have any clue as to why we receive those b"\xff" messages, we will investigate further. 

Kind regards and thanks for your work,

Konrad

**Comment by electronsandstuff** [comment]
Thanks for submitting this issue and glad to see people are using the library!

That's pretty strange that you're getting those characters from the serial adapter. However, your solution seems like a pretty good fix and should be easy to implement. I'll go ahead and work on adding it as an extra option to the library. I don't think that filtering should be turned on by default since I am worried it could hide real errors from other users. I am thinking of some sort of global way of doing it with options to override in the functions.

```python
pfeiffer_vacuum_protocol.enable_valid_char_filter()
pfeiffer_vacuum_protocol.disable_valid_char_filter()
read_pressure(ser, addr, valid_char_filter=True)  # True, False, or None for global default
```

I will also probably add a custom message for the decode error you got letting users know that the character filter exists and telling them to try it out to see if it solves the issue.

**Comment by Nothinel** [comment]
Thanks for the reaction!

I am not sure about the perfect solution, but the interface on the user side seems straight forward enough with your approach, that we would absolutley switch back to you main branch, if this is implemented. 

Internally one could use errorhandling for the `c.decode()` function and either raise the error or reduce it to a run time warning, based on the `valid_char_filter` parameter. This would enable users (like us) to just "ignore" anything that does not decode to ASCII, while still keeping the user informed about what exactly their system receives in terms of messages.

**Comment by electronsandstuff** [comment]
Ok, I think that should work. It should also be up on pypi now, so you can upgrade using pip. Also ended up doing a bunch of code cleanup since I wrote this a long time ago. Hope this works for you!
